### ISSUE TITLE
i18n translation coverage very patchy

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-campaign-admin#105]
I've set my demo site in French and looking at the Campaign Admin module, the translation coverage is very patchy. In most cases, the translations haven't been properly set up under `client/lang/src/en.json` so Transifex isn't picking up that there's strings to translate.

![screenshot from 2018-06-18 15-48-39](https://user-images.githubusercontent.com/1168676/41517929-f06efcd4-7312-11e8-89fb-ac2e3e7166b2.png)
![screenshot from 2018-06-18 15-49-27](https://user-images.githubusercontent.com/1168676/41517930-f09b2a0c-7312-11e8-89a8-cef1407147e0.png)

**Comment by robbieaverill** [comment]
Oh, I fixed this in #96 by adding the rest of the translations to the source dictionary

**Comment by maxime-rainville** [comment]
Merci.
