### ISSUE TITLE
Cannot vertically scroll with intro welcome message on vertically small screen

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-campaign-admin#121]
![image](https://user-images.githubusercontent.com/5170590/45627367-1aa7db80-ba92-11e8-890a-a01d7bcdbdc1.png)

SS 4.3.x-dev

If my viewport is the size in the screenshot then I can't scroll down to see what campaigns I have. It made me think I didn't have any. It looks like the splash message has a fixed height while the list of campaigns has `panel--scrollable` attached to it so it can be scrolled. Perhaps we should make the whole panel scrollable...?

cc @clarkepaul 

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/132

**Comment by clarkepaul** [comment]
Yeah, there is no reason the splash banner needs to be fixed, its probably not placed inside the scrollable area. Hopefully it can be moved without too much effort.

**Comment by robbieaverill** [comment]
👍 also the workaround is to manually close the splash

**Comment by robbieaverill** [comment]
Easy enough - the padding and scrollable containers can be split and chuck the intro screen in between them. PR at #132

**Comment by ScopeyNZ** [comment]
Closed by #132
