### ISSUE TITLE
Better help and guidance for the Campaigns section

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-campaign-admin#127]
The Campaigns section is still a new and needs explaining what the intention of the area is. We should either provide more context or at least provide links to user help so people can figure it out.

This issue is to add more written context or links from the Campaign intro area to the User Help [as per designs](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5be249579efd15001bb0a4d4). 

What exists now:
![image](https://user-images.githubusercontent.com/555033/51219072-0ae2ca00-1994-11e9-9b5e-5456924ba141.png)

The design which was created (using mock content):
![image](https://user-images.githubusercontent.com/555033/51218811-e20e0500-1992-11e9-9c7d-bd4677b240b7.png)

Implementation notes
- Find the most important links to show - user help is key here.
- Display the links on the campaign introduction
- Proposed links: Adding items to a campaign; Managing items within campaign

Proposed button:
Campaign user help

# PR's

- [ ] https://github.com/silverstripe/silverstripe-campaign-admin/pull/168

**Comment by clarkepaul** [comment]
Related to https://github.com/silverstripe/silverstripe-admin/issues/270 for the functionality.

**Comment by newleeland** [comment]
Just to update where this story is at:
- Userhelp of campaigns have been created, however all the content is located on one page without anchor tags.
- Therefore the design needs to be updated accommodate the change in content

**Comment by emteknetnz** [comment]
@clarkepaul implemented in https://github.com/silverstripe/silverstripe-campaign-admin/pull/168

**Comment by emteknetnz** [comment]
This has been fixed, will be released with the next minor
