### ISSUE TITLE
Remove unneeded content types being added to Campaigns

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-campaign-admin#128]
## Description

When a page with content blocks is added to a campaign, extra content types appear within the campaign ("Elemental Areas" and "File links"), which are really confusing for the user as they are not campaignable/publishable items

#### User Story
As a user viewing items slated for a campaign, I only want to see items that are publishable on their own, so that I do not get confused with the detail of what's being published.

#### ACs
- [x] I do not see Elemental areas: resolved in https://github.com/dnadesign/silverstripe-elemental/issues/593
- [x] I do not see File Links
- [ ] I have enough context to know which items are part of a content block, or other data object, or they are not included
- [ ] Add some documentation so developers know how to show/hide their custom objects

#### Notes
- We've decided on creating a new API and taking a step back to ensure this is done correctly, vs. 'simpler' dataobject filtering

## Steps to Reproduce

1. In Campaigns, click Add Campaign
2. Go to a page with content blocks.
3. Click Add to Campaign that you just created
4. Go the Campaign and view the extra items

## Affected Version

SilverStripe 4.x

**Comment by brynwhyman** [comment]
This sounds pretty closely related to: https://github.com/silverstripe/silverstripe-asset-admin/issues/903, which is also dealing with verbose information of individual objects.

We've been talking about implementing an API that only includes 'user facing' classes, this could be used in places like campaigns, reports.

**Comment by clarkepaul** [comment]
I think this might have been resolved to the point this issue can be closed, the likes of Elemental Areas and file links don't show anymore.
