### ISSUE TITLE
Content blocks with "Untitled" titles appear to have blank titles when viewed in campaigns

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-campaign-admin#129]
## Description
When a content block is added to a campaign and the block does not have a given title it appears blank. The block should use the *Untitled* title set by the CMS when user has not given the block a title.

## How to reproduce
- In Campaigns, Add Campaign
- In Pages, select a page with content blocks without a title and Add to campaign that was created.
- Go back to Campaigns and view content block in the campaign

## Affected Versions
SS 4.x

**Comment by clarkepaul** [comment]
Raised in Elemental as well as it should probably be the repo which should have this issue https://github.com/dnadesign/silverstripe-elemental/issues/574

**Comment by bergice** [comment]
Resolved with https://github.com/silverstripe/silverstripe-campaign-admin/pull/171
