### ISSUE TITLE
Add to campaign modal can't be closed

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-campaign-admin#13]
After adding to a campaign the "close" button is covered up. Can be exited by pressing escape.

![image](https://cloud.githubusercontent.com/assets/936064/25572471/857af37e-2e8f-11e7-9db7-63de3ec0c4e8.png)

**Comment by flamerohr** [comment]
Pull request https://github.com/silverstripe/silverstripe-admin/pull/49

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-admin/pull/49#pullrequestreview-35542130
