### ISSUE TITLE
Add to campaign list shouldn't include inferred change sets

### ISSUE THREAD

**Issue by mxmclaudel** [silverstripe/silverstripe-campaign-admin#148]
When adding an item to a campaign, the campaigns listed are all ChangeSet where state = open.
it should also exclude inferred ones.
The campaign admin does exclude them, the "Add to campaign" handler doesn't.
This can result in campaigns being listed that can't be managed anyway.

# Pull Requests
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/149 (closed)
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/150

**Comment by mxmclaudel** [comment]
PR #149

**Comment by bergice** [comment]
Merged into `1.5`.
