### ISSUE TITLE
"Add to Campaign" button appears even if member doesn't have Campaign permissions

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-campaign-admin#19]
If *Access to 'Campaigns' section* (CMS_ACCESS_CampaignAdmin) is disabled for a member or group in Security, those members still see the "Add to Campaign" option in a page's "More options" menu. But this option is redundant, as without the permission the "Available campaigns" dropdown box that appears after clicking the option is always empty.

So if a user doesn't have CMS_ACCESS_CampaignAdmin permission, the "Add to Campaign" option shouldn't appear.

May be related to #1 

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-cms/pull/2382
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/134

**Comment by purplespider** [comment]
This still occurs in v4.0.0-rc1. Users without Campaigns permissions (e.g. those in the default Content Authors group), still see the "App to Campaign" option in the "..." menu.

(Although it now does display a "Your current login does not have privileges to create campaigns." error, but the option really shouldn't display at all.)

**Comment by robbieaverill** [comment]
Arghhhh it's in SiteTree. I'll make a minor change PR to move it to an extension.

**Comment by robbieaverill** [comment]
All PRs merged (with the bugfix and decoupling)
