### ISSUE TITLE
Broken build - behat failure: manage campaigns feature

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-campaign-admin#201]
--- Failed scenarios:
    tests/behat/features/manage-campaigns.feature:21

https://travis-ci.com/github/silverstripe/silverstripe-campaign-admin/jobs/503802358

## Notes
- There is also a GraphQL v4 specific failure, captured here: https://github.com/silverstripe/silverstripe-campaign-admin/issues/192

**Comment by bergice** [comment]
This is resolved.
