### ISSUE TITLE
Inferred Chanset can be viewed in campaigned admin

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-campaign-admin#204]
# Description

When you publish a page, it creates an "Infered" changeset object. This ChangeSet can be access by ID in campaign admin and you get an error when you try to interact with it.

# Steps to reproduce
- Publish a page
- Look up the latest ID of your changeset in the DB
- Access the campaign with this ID in Campaign-admin

Expected outcome: You get a 400/404 error page
Actual: You see a campaign

## Acceptance criteria
- [ ] Campaign admin does not let you directly access inferred change set as campaigns.
- [ ] A reasonable error is shown if you try to directly access an inferred change set and a proper HTTP error code is returned.
- [ ] Inferred change set are not shown in the campaign list.
- [ ] If this feature uses a GraphQL query, both GraphQL v3 and v4 refuse to returned inferred change set.

## Pull request
- [ ] https://github.com/silverstripe/silverstripe-campaign-admin/pull/228

**Comment by sabina-talipova** [comment]
Sequencing:
1. Filter the changeSet in the CampaignAdmin class by IsInferred === false **(? Find out the purpose of IsInferred)**
2. If the passed ID does not exist or the ID did not pass the filter, return 404.
3. In the CampaignAdminList React Component, catch the 404 and return the appropriate content.

**Comment by maxime-rainville** [comment]
Just summarizing some discussion @sabina-talipova had today.

For our use case, it's probably not worthwhile differentiating between the scenario where the user asks for a non-existent changeset and for an existing _inferred_ change set.

I'll see if I can get some design review for the 404 error page. Maybe post a screen shot of what it currently looks like in your PR for now.

Adding some Behat test to cover this possibility is probably more of a nice-to-have, but it's a good way to get your behat set up working.
