### ISSUE TITLE
Save button on add/edit campaign should update to "Saved" 

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-campaign-admin#25]
The save button text should update to "Saved [green text]" like the pages buttons if saved successfully, but change back to "Save [green background]" if further changes are detected.
<img width="221" alt="pasted_image_26_05_17__12_16_pm" src="https://cloud.githubusercontent.com/assets/555033/26475678/43b6c026-420d-11e7-9bc8-370b6a7b1202.png">

**Comment by chillu** [comment]
Note that this should be consistent throughout the CMS, across React and non-React sections

**Comment by newleeland** [comment]
## ACs (Potential)
- I want to see a confirmation message on the Save/Publish button when I've updated details anywhere within the CMS
### Default
![screen_shot_2017-08-29_at_13_55_16](https://user-images.githubusercontent.com/8085295/29801359-4803b804-8cc3-11e7-9816-f16c4ff71a91.png)

### After details are updated (Confirmation message)
![screen_shot_2017-08-29_at_13_55_08](https://user-images.githubusercontent.com/8085295/29801360-480880d2-8cc3-11e7-9ed5-aca9122b3f22.png)

**Comment by flamerohr** [comment]
Fixed by https://github.com/silverstripe/silverstripe-admin/pull/216/files#diff-7eed84efcf9a5970aee3afb2aa621b33R122
