### ISSUE TITLE
TODO: CampaignAdmin::getClientConfig - use schemaUrl instead

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-campaign-admin#281]
## Description
See: https://github.com/silverstripe/silverstripe-campaign-admin/blob/56b20388f355b724864207bf1f2bbf761b0c7233/src/CampaignAdmin.php#L84

**Comment by GuySartorelli** [comment]
@sabina-talipova I'm not really sure what this means... "schemaUrl" is the key in the associative array, so if that isn't what is meant by "use schemaUrl" then what is? This might be one we don't have enough context on and should close.

**Comment by sabina-talipova** [comment]
> This might be one we don't have enough context on and should close.

Agree.
