### ISSUE TITLE
Content author should not be able to remove Campaign items after publishing

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-campaign-admin#287]
## Story
As a content author, I want campaigns to reflect the items that were assigned to them at publication time so I have an accurate historical record.

## Description
- Create a campaign and add items to to it.
- Publish the campaign.
- Navigate to the campaign page.

Expected: Campaign doesn't let me remove items and no actions are showed.
Actual: Action to remove campaign item are available and functional.

## Acceptance criteria
- API endpoints to remove items from campaign return 400 errors when called on a published campaign.
- UI doesn't offer actions to remove items if the campaign has been published.

## Note

The more actions menu is the "3 dots" button

![image](https://github.com/silverstripe/silverstripe-campaign-admin/assets/4809037/14a15f17-e1ef-4bd4-a79e-f9d3c829f7ca)

## PR
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/288

**Comment by emteknetnz** [comment]
Linked PR has been merged
