### ISSUE TITLE
Add a clearer indication a campaign has been saved

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-campaign-admin#36]
If a campaign is saved we are showing the loading indicator but not formally saying it has work.

We could do one of the following to improve its usability:
* Change the button label from "Save" to "Saved" as per pages actions
* Show a notification message using one of the established patterns in the CMS (top of form or top right of viewport)
* Direct the user back to the campaign with a notification at the top of the campaign

**Comment by flamerohr** [comment]
@clarkepaul this could be discussed as part of the original ticket https://github.com/silverstripe/silverstripe-campaign-admin/issues/16

**Comment by clarkepaul** [comment]
Cool if you think so, I'll close this and move it to the other issue and add as task.
