### ISSUE TITLE
Campaign disappears from campaigns list when published

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-campaign-admin#38]
## Background
Through user testing, I observed that users were confused when the campaign was gone and there was no notification or indication that it would disappear. There will be times when campaigns will want to be kept so they don't need to be rebuilt every time the content is published. 

A simple scenario of this might be that a business releases new product prices on a monthly basis, the contents of the campaign would be kept the same every time the campaign is released but the prices would be adjusted and scheduled at a certain date. This pattern could apply to sections of a site as well like news, events and will become more useful once campaigns have group permissions eg HR admins only have access to the staff area of a website so they can have a staff campaign.

I suggest we have options to keep or delete (with a clear indication that it doesn't delete its contents) the campaign once published.

## ACs
 * I should be able to see campaigns which have been published if they have not been deleted
 * I should be able to see campaigns that have not yet been published
 * I can see when a campaign was published (and who published it) in the table and "campaign settings" view

## Notes

 * This requires a datamodel addition for `ChangeSet.PublisherID` and `ChangeSet.PublishedDate`. 
 * Excludes "I can publish a campaign multiple times" (that's requiring a more complex data model). We'll allow duplicating campaigns instead, see https://github.com/silverstripe/silverstripe-campaign-admin/issues/45
 * Given the "revert" button is currently non-functional, we should proably remove it to avoid confusion

## Prototype
https://invis.io/A7D46RYZ8#/249478439_Campaigns_-_Listings_-_Dashboard

## Related
 * [Ability to revert/unrelease a campaign](https://github.com/silverstripe/silverstripe-campaign-admin/issues/43)
 * [Duplicate campaign](https://github.com/silverstripe/silverstripe-campaign-admin/issues/45).

## Pull Requests:
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/46
- [x] https://github.com/silverstripe/silverstripe-versioned/pull/39

**Comment by newleeland** [comment]
I'd imagine if this story (#43) is completed, it would resolve this story.

**Comment by newleeland** [comment]
I think this has the potential to affects a lot of areas. e.g. the quick campaign creation on pages (https://github.com/silverstripe/silverstripe-admin/issues/161) There are a few ways we can approach this:
- Get the campaign to remain by default, so there's one less thing for users to think about. The user currently has the ability to delete these campaign if they so wished.
- Have the ability to create recurring campaigns during, campaign creation.
- Have the ability to create recurring campaigns before, campaign publishing.

**Comment by clarkepaul** [comment]
> I'd imagine if this story (#43) is completed, it would resolve this story.
This is different functionality and wouldn't resolve this issue

@newleeland I'm not sure I follow the three ways you've described that we can approach this so would be good to go over this a bit more with you. 

On publishing the campaign we could offer the user two options "Publish and keep campaign open [default]" and "Publish and archive".

**Comment by newleeland** [comment]
@clarkepaul I've removed the confirmation modal all together for now as it does not provide enough and having a discard button may confuse the user that they should "discard" their campaign (as per our discussion)

**Comment by chillu** [comment]
I agree that the campaign shouldn't just disappear from the list, that's counterintuitive (and easy to fix). It might need more indication on the campaign table and detail screen that the campaign has been published (when/who).

I would like to see more proof that users want campaigns to be persistent buckets which can be re-published periodically. It's yet another decision point for users between "publish/keep" and "publish/archive", and has the potential to clutter up the campaigns dropdown. So lots of downstream complexity as well (e.g. a lazy loaded and searchable campaigns dropdown). @clarkepaul @newleeland did you have specific user feedback requesting repeat publish of campaigns?

**Comment by clarkepaul** [comment]
@chillu no definitive results as yet on whether campaigns should be reusable or not. The campaigns section has been built more on our wanting to provide more clarity on complex relationships rather than user feedback for bulk publishing although some users have indicated it could be of use but they would need to try it with their own content rather than a user test with mock data. When I have provided suggestions for how it could be used users have indicated that it could be useful but not sure as yet if/when they would actually use it.

I see the value for when a campaign has a lot of items which would regularly be updated (eg pricing changes, product list) or a section of a site which someone has ownership of and you don't want to rebuild the campaign every time with the same items. As we don't have any campaign history as yet or records of what was published I think it is valuable to let users look back and confirm what was published (as a soft form of campaign history). 

I see this as one of the last steps to actually make the Campaign section make sense as part of a MVP (I don't see this as a nice to have but more of a necessity for clarity).

If a user publishes a campaign they should be given the option to "Publish and discard" the campaign so that the campaign list remains clean (this could even be the default option).

@newleeland can you add the column "Published by" to the mock please.

**Comment by newleeland** [comment]
I've just added them to the prototype. This would also remedy #43. If you're happy with the changes @clarkepaul @chillu, I'll move it into next.
![screen shot 2017-08-22 at 3 20 31 pm](https://user-images.githubusercontent.com/8085295/29547322-790da3c2-874d-11e7-9d2e-bffd412909d1.png)

**Comment by chillu** [comment]
Old ACs

 * I should be able to see campaigns which have been published if they have not been deleted
 * I should be able to see campaigns that have not yet been published
 * I can review and make changes to my campaigns (i.e. Edit/Preview/Remove items) for publishing

New ACs

 * I should be able to see campaigns which have been published if they have not been deleted
 * I should be able to see campaigns that have not yet been published
 * I can publish a campaign multiple times
 * I can see when a campaign was last published (and who published it) in the table and "campaign settings" view

**Comment by chillu** [comment]
@newleeland I've removed the tasks, since they were sneaking in more features and acceptance criteria. Switching between 'publish' and 'published' button labels is unfortunately a bit difficult at the moment, so we're not doing that as part of the MVP. For now, you get a loading indicator during publish, and the button goes back to the original state.

**Comment by sminnee** [comment]
It seems to me that a core part of the confusion is that the campaign disappeared from the list instead of continuing to be listed with status = "Published".

Perhaps this card should be restricted to that and "I can publish a campaign multiple times" shifted to #45?

**Comment by chillu** [comment]
Based on yesterday's discussion on Slack, I've removed "I can publish a campaign multiple times", and propose we solve this use case by allowing duplication of campaigns instead: https://github.com/silverstripe/silverstripe-campaign-admin/issues/45.
