### ISSUE TITLE
After publishing a campaign give users the choice to delete or keep the campaign

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-campaign-admin#44]
To keep the list of campaigns in a manageable state, we should give users the opportunity to archive a campaign once they have published it. If the campaign is to be a recurring campaign then users can decide to keep the campaign open so that it can be reused. This will help to keep the open list of campaigns relevant and manageable.

Provide two options once the "Publish campaign" button is clicked (terminology only suggestions).
* Keep this campaign open for re-use
* Close this campaign

Or probably a better pattern is to use the buttons as a confirmation of publishing the campaign.
* Publish and keep campaign open for re-use
* Publish then discard campaign

**Comment by newleeland** [comment]
Those that are quite long
1. [Publish and keep]    [Discard once published]
2. [Publish]    [Discard on publishing]   <-- "Publish" implies that we keep, as the other is explicitly "discard

**Comment by clarkepaul** [comment]
This issue doesn't have as much relevance now that we have a history of campaigns which are not editable. Deleting the history when publishing is not a pattern we should encourage. I'm closing this issue but will open a new issue to show either a confirmation dialog or undo action when the publish button is clicked. See https://github.com/silverstripe/silverstripe-campaign-admin/issues/50
