### ISSUE TITLE
Campaign overview: Clear indication of "Work in Progress"

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-campaign-admin#53]
# Acceptance Criteria

 * I can clearly distinguish between unpublished and published campaigns in the table view

# Notes

 * Designs at https://invis.io/8HD9ADEPR#/250964968_Campaigns_-_List_-_Dashboard_V2
 * Discussion in https://github.com/silverstripe/silverstripe-campaign-admin/issues/45 for additional context

## Pull requests

 - [x] https://github.com/silverstripe/silverstripe-admin/pull/366
 - [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/81

**Comment by phalkunz** [comment]
Had a discussion with @newleeland and @clarkepaul, the text should be "Active" instead "Work in progress" for open campaign.

@clarkepaul also mentioned the status color badge is too big so I use 10px instead 12px.

**Comment by clarkepaul** [comment]
It not that I'm against "Work in progress" but we are possibly going to introduce a soft form of workflow which would likely use the term "Work in progress" with the meaning content is incomplete and not ready for publishing. I'm open to other terminology but I'm not sure which is best from "Open" or "Active", but I do know "work in progress" isn't right.

**Comment by clarkepaul** [comment]
Perhaps we should be thinking about this in terms of a "draft campaign" and "published campaign".
