### ISSUE TITLE
BUG No error message when adding a duplicate campaign on Add to campaign modal

### ISSUE THREAD

**Issue by phalkunz** [silverstripe/silverstripe-campaign-admin#57]
## Steps to reproduce:

1. Create a campaign called "New"
1. Go to __Pages__ section
1. Select Home page
1. Bring up __Add To Campaign__ modal
1. Select __Add to a new campaign__ checkbox
1. Enter "New" in __Create a new campaign__ text field
1. Click __Add__ button
1. Observe that the modal stays home and there's an error ("Uncaught (in promise) Error: Internal Server Error") in the browser console

Pull request:

- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/79

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-campaign-admin/pull/79
