### ISSUE TITLE
Can't see Files move button

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-campaign-admin#61]
Arrow is hard to see when moving files that nested. Changing it to white make it more visible

![screen_shot_2017-09-11_at_2_46_47_pm](https://user-images.githubusercontent.com/8085295/30256646-5a839782-9700-11e7-83d9-52e0b489153e.png)

**Comment by clarkepaul** [comment]
Closing as this is already captured as part of another issue https://github.com/silverstripe/silverstripe-admin/issues/231
