### ISSUE TITLE
Placement of preview back button

### ISSUE THREAD

**Issue by phalkunz** [silverstripe/silverstripe-campaign-admin#68]
![silverstripe_-_campaigns](https://user-images.githubusercontent.com/318116/31257518-6f2ae390-aa95-11e7-9192-596907294570.png)

**Comment by robbieaverill** [comment]
This button doesn't exist any more since we've added the view mode switcher/toggle:

https://github.com/silverstripe/silverstripe-campaign-admin/pull/132
