### ISSUE TITLE
Icons missing from font library

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-campaign-admin#76]
Tested on UAT, .font-icon-white-question seems missing in icon set
<img width="79" alt="pasted_image_7_11_17__3_01_pm" src="https://user-images.githubusercontent.com/555033/32473456-79dfa438-c3cc-11e7-8f3e-ac5bcf26677b.png">
<img width="114" alt="pasted_image_7_11_17__2_58_pm" src="https://user-images.githubusercontent.com/555033/32473612-3c81ba94-c3cd-11e7-83db-fe0e951f4e6a.png">

**Comment by flamerohr** [comment]
it's there, but you have to clear your cache on Chrome before it appears
