### ISSUE TITLE
Help icon is not centered horizontally

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-campaign-admin#86]
Add the class .btn--no-text to the button so that it removes the space which typically sits between the icon and text.

![image](https://user-images.githubusercontent.com/555033/35305780-97dc39d6-00ff-11e8-9f8f-a3d6734e0918.png)

**Comment by tractorcow** [comment]
The help close button is also super-impossible to see.

![image](https://user-images.githubusercontent.com/936064/38065563-854f1f84-3360-11e8-87cc-b802ffe2b13b.png)

**Comment by tractorcow** [comment]
Easier to see on hover

![image](https://user-images.githubusercontent.com/936064/38065569-8f594b12-3360-11e8-8e4e-0d08f040258f.png)
