### ISSUE TITLE
Preview of new campaign not responsive

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-campaign-admin#87]
![image](https://user-images.githubusercontent.com/555033/35305960-6a23a686-0100-11e8-9b60-60e013cbde4b.png)

There should be padding left and right and cantered text all the time unless the design specified something different. @newleeland can you see if something was specified for smaller viewports.

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/133
- [x] https://github.com/silverstripe/silverstripe-admin/pull/818
- [x] silverstripe/silverstripe-campaign-admin#141
- [x] silverstripe/silverstripe-versioned-admin#108

**Comment by robbieaverill** [comment]
PRs posted in the issue description

**Comment by robbieaverill** [comment]
ResizeAware polyfill for Firefox support wasn't implemented in campaign or versioned admin, I've added PRs for those

**Comment by robbieaverill** [comment]
All merged
