### ISSUE TITLE
BUG Campaign gridfield has broken margin

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-campaign-admin#91]
![image](https://user-images.githubusercontent.com/936064/38065599-ab8cd218-3360-11e8-8ca3-52b765d972a4.png)

Should be easy to fix

Affected in 1.x-dev branch.

**Comment by unclecheese** [comment]
Blocked until https://github.com/silverstripe/silverstripe-asset-admin/issues/774 is merged

**Comment by dhensby** [comment]
https://github.com/silverstripe/silverstripe-asset-admin/issues/774 is an issue, not a PR
