### ISSUE TITLE
BUG Weird scrollbar on nearly every campaign admin section

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-campaign-admin#92]
![image](https://user-images.githubusercontent.com/936064/38065664-ed53e4a2-3360-11e8-9bb3-9f5a205cf8a6.png)

1.x-dev branch

**Comment by chillu** [comment]
There's also vertical scrollbars

![image](https://user-images.githubusercontent.com/111025/51095214-fc6fa380-1817-11e9-9636-54ef7a2ae7a9.png)

**Comment by robbieaverill** [comment]
I accidentally fixed the vertical scrollbar bug in #132. I can't reproduce the horizontal scrollbars any more.

**Comment by chillu** [comment]
The vertical scrollbars are still there, and they look a bit whacky. But it can be "fixed" by dismissing the dialog, which most people using this section will do on first opening it. So I'm going to close this
